### ISSUE TITLE
WorkflowyMd.js not working

### ISSUE THREAD

**Issue by rubaboo** [Wizmann/Utils#3]
Any chance you could fix `WorkflowyMd.js` userscript? It doesn't work, I'm guessing there were some changes in WF structure.

**Comment by Wizmann** [comment]
let me check...

**Comment by Wizmann** [comment]
it's because workflowy removed jquery, add it back will fix the problem.


![image](https://user-images.githubusercontent.com/1270921/150106970-45f25dba-e323-44b9-a803-e6eeea90a7c5.png)

**Comment by Wizmann** [comment]
close the issue if it works :)

**Comment by rubaboo** [comment]
Thank you very much!
